// Re-export all types from the shared package
export type {
  Role,
  Permission,
  LeadPayload,
  UserProfile,
  LeadStatus,
  Lead,
  LeadNote,
  Client,
  ClientContact,
  ProposalStatus,
  Proposal,
  ProposalItem,
  ProjectStatus,
  Project,
  ProjectPhase,
  TaskPriority,
  TaskStatus,
  Task,
  InvoiceStatus,
  Invoice,
  ActivityAction,
  ActivityLog,
} from "@nextops/shared";
